# vim:set ft=sh:
MODULES=(fuse ext4 fat vfat)
BINARIES=(mount.ntfs-3g mount.ntfs mount.fuse fsck.ext4 fsck.fat fsck.vfat) 
FILES=()
HOOKS=(base systemd autodetect microcode modconf kms keyboard sd-vconsole block fsck)